version: '3.8'

services:
  whatsapp-webjs-wrapper-bot-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-webjs-wrapper-bot-server
    ports:
      - '6662:6662'
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
